# Generated by Django 3.2.6 on 2021-10-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='image',
            field=models.FilePathField(path='C:\\Users\\vader227\\Django\\rp-portfolio\\hobby\\img'),
        ),
    ]
